/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SaveEther } from "./SaveEther";
export * as factories from "./factories";
export { SaveEther__factory } from "./factories/SaveEther__factory";
